/* oxlint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as SitemapDotxmlRouteImport } from "./routes/sitemap[.]xml";
import { Route as RobotsDottxtRouteImport } from "./routes/robots[.]txt";
import { Route as PrivacyRouteImport } from "./routes/privacy";
import { Route as MarketplaceRouteImport } from "./routes/marketplace_";
import { Route as LinkRouteImport } from "./routes/link";
import { Route as DashboardRouteImport } from "./routes/dashboard";
import { Route as ChangelogRouteImport } from "./routes/changelog";
import { Route as BlogRouteImport } from "./routes/blog";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as MarketplacePluginIdRouteImport } from "./routes/marketplace_.$pluginId";
import { Route as DownloadMacosRouteImport } from "./routes/download.macos";
import { Route as DownloadLinuxRouteImport } from "./routes/download.linux";
import { Route as BlogSlugRouteImport } from "./routes/blog_.$slug";
import { Route as ApiSubscribeRouteImport } from "./routes/api.subscribe";
import { Route as DotwellKnownAssetlinksDotjsonRouteImport } from "./routes/[.]well-known.assetlinks[.]json";
import { Route as DotwellKnownAppleAppSiteAssociationRouteImport } from "./routes/[.]well-known.apple-app-site-association";
import { Route as MarketplaceAuthorGithubRouteImport } from "./routes/marketplace_.author.$github";
import { Route as MarketplaceV2SplatRouteImport } from "./routes/marketplace.v2.$";
import { Route as MarketplaceV1SplatRouteImport } from "./routes/marketplace.v1.$";
import { Route as MarketplaceOgPluginIdRouteImport } from "./routes/marketplace.og.$pluginId";
import { Route as ApiConnectRevokeMachineRouteImport } from "./routes/api.connect.revoke-machine";
import { Route as ApiConnectRedeemMachineRouteImport } from "./routes/api.connect.redeem-machine";
import { Route as ApiConnectRedeemRouteImport } from "./routes/api.connect.redeem";
import { Route as ApiConnectMachineCodeLookupRouteImport } from "./routes/api.connect.machine-code-lookup";
import { Route as ApiConnectMachineCodeRouteImport } from "./routes/api.connect.machine-code";
import { Route as ApiAuthSplatRouteImport } from "./routes/api.auth.$";
import { Route as ApiAccountMeRouteImport } from "./routes/api.account.me";
import { Route as ApiAccountLinkStartRouteImport } from "./routes/api.account.link.start";
import { Route as ApiAccountLinkPollRouteImport } from "./routes/api.account.link.poll";

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: "/sitemap.xml",
  path: "/sitemap.xml",
  getParentRoute: () => rootRouteImport,
} as any);
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: "/robots.txt",
  path: "/robots.txt",
  getParentRoute: () => rootRouteImport,
} as any);
const PrivacyRoute = PrivacyRouteImport.update({
  id: "/privacy",
  path: "/privacy",
  getParentRoute: () => rootRouteImport,
} as any);
const MarketplaceRoute = MarketplaceRouteImport.update({
  id: "/marketplace_",
  path: "/marketplace",
  getParentRoute: () => rootRouteImport,
} as any);
const LinkRoute = LinkRouteImport.update({
  id: "/link",
  path: "/link",
  getParentRoute: () => rootRouteImport,
} as any);
const DashboardRoute = DashboardRouteImport.update({
  id: "/dashboard",
  path: "/dashboard",
  getParentRoute: () => rootRouteImport,
} as any);
const ChangelogRoute = ChangelogRouteImport.update({
  id: "/changelog",
  path: "/changelog",
  getParentRoute: () => rootRouteImport,
} as any);
const BlogRoute = BlogRouteImport.update({
  id: "/blog",
  path: "/blog",
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const MarketplacePluginIdRoute = MarketplacePluginIdRouteImport.update({
  id: "/$pluginId",
  path: "/$pluginId",
  getParentRoute: () => MarketplaceRoute,
} as any);
const DownloadMacosRoute = DownloadMacosRouteImport.update({
  id: "/download/macos",
  path: "/download/macos",
  getParentRoute: () => rootRouteImport,
} as any);
const DownloadLinuxRoute = DownloadLinuxRouteImport.update({
  id: "/download/linux",
  path: "/download/linux",
  getParentRoute: () => rootRouteImport,
} as any);
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: "/blog_/$slug",
  path: "/blog/$slug",
  getParentRoute: () => rootRouteImport,
} as any);
const ApiSubscribeRoute = ApiSubscribeRouteImport.update({
  id: "/api/subscribe",
  path: "/api/subscribe",
  getParentRoute: () => rootRouteImport,
} as any);
const DotwellKnownAssetlinksDotjsonRoute =
  DotwellKnownAssetlinksDotjsonRouteImport.update({
    id: "/.well-known/assetlinks.json",
    path: "/.well-known/assetlinks.json",
    getParentRoute: () => rootRouteImport,
  } as any);
const DotwellKnownAppleAppSiteAssociationRoute =
  DotwellKnownAppleAppSiteAssociationRouteImport.update({
    id: "/.well-known/apple-app-site-association",
    path: "/.well-known/apple-app-site-association",
    getParentRoute: () => rootRouteImport,
  } as any);
const MarketplaceAuthorGithubRoute = MarketplaceAuthorGithubRouteImport.update({
  id: "/author/$github",
  path: "/author/$github",
  getParentRoute: () => MarketplaceRoute,
} as any);
const MarketplaceV2SplatRoute = MarketplaceV2SplatRouteImport.update({
  id: "/marketplace/v2/$",
  path: "/marketplace/v2/$",
  getParentRoute: () => rootRouteImport,
} as any);
const MarketplaceV1SplatRoute = MarketplaceV1SplatRouteImport.update({
  id: "/marketplace/v1/$",
  path: "/marketplace/v1/$",
  getParentRoute: () => rootRouteImport,
} as any);
const MarketplaceOgPluginIdRoute = MarketplaceOgPluginIdRouteImport.update({
  id: "/marketplace/og/$pluginId",
  path: "/marketplace/og/$pluginId",
  getParentRoute: () => rootRouteImport,
} as any);
const ApiConnectRevokeMachineRoute = ApiConnectRevokeMachineRouteImport.update({
  id: "/api/connect/revoke-machine",
  path: "/api/connect/revoke-machine",
  getParentRoute: () => rootRouteImport,
} as any);
const ApiConnectRedeemMachineRoute = ApiConnectRedeemMachineRouteImport.update({
  id: "/api/connect/redeem-machine",
  path: "/api/connect/redeem-machine",
  getParentRoute: () => rootRouteImport,
} as any);
const ApiConnectRedeemRoute = ApiConnectRedeemRouteImport.update({
  id: "/api/connect/redeem",
  path: "/api/connect/redeem",
  getParentRoute: () => rootRouteImport,
} as any);
const ApiConnectMachineCodeLookupRoute =
  ApiConnectMachineCodeLookupRouteImport.update({
    id: "/api/connect/machine-code-lookup",
    path: "/api/connect/machine-code-lookup",
    getParentRoute: () => rootRouteImport,
  } as any);
const ApiConnectMachineCodeRoute = ApiConnectMachineCodeRouteImport.update({
  id: "/api/connect/machine-code",
  path: "/api/connect/machine-code",
  getParentRoute: () => rootRouteImport,
} as any);
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: "/api/auth/$",
  path: "/api/auth/$",
  getParentRoute: () => rootRouteImport,
} as any);
const ApiAccountMeRoute = ApiAccountMeRouteImport.update({
  id: "/api/account/me",
  path: "/api/account/me",
  getParentRoute: () => rootRouteImport,
} as any);
const ApiAccountLinkStartRoute = ApiAccountLinkStartRouteImport.update({
  id: "/api/account/link/start",
  path: "/api/account/link/start",
  getParentRoute: () => rootRouteImport,
} as any);
const ApiAccountLinkPollRoute = ApiAccountLinkPollRouteImport.update({
  id: "/api/account/link/poll",
  path: "/api/account/link/poll",
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/blog": typeof BlogRoute;
  "/changelog": typeof ChangelogRoute;
  "/dashboard": typeof DashboardRoute;
  "/link": typeof LinkRoute;
  "/marketplace": typeof MarketplaceRouteWithChildren;
  "/privacy": typeof PrivacyRoute;
  "/robots.txt": typeof RobotsDottxtRoute;
  "/sitemap.xml": typeof SitemapDotxmlRoute;
  "/.well-known/apple-app-site-association": typeof DotwellKnownAppleAppSiteAssociationRoute;
  "/.well-known/assetlinks.json": typeof DotwellKnownAssetlinksDotjsonRoute;
  "/api/subscribe": typeof ApiSubscribeRoute;
  "/blog/$slug": typeof BlogSlugRoute;
  "/download/linux": typeof DownloadLinuxRoute;
  "/download/macos": typeof DownloadMacosRoute;
  "/marketplace/$pluginId": typeof MarketplacePluginIdRoute;
  "/api/account/me": typeof ApiAccountMeRoute;
  "/api/auth/$": typeof ApiAuthSplatRoute;
  "/api/connect/machine-code": typeof ApiConnectMachineCodeRoute;
  "/api/connect/machine-code-lookup": typeof ApiConnectMachineCodeLookupRoute;
  "/api/connect/redeem": typeof ApiConnectRedeemRoute;
  "/api/connect/redeem-machine": typeof ApiConnectRedeemMachineRoute;
  "/api/connect/revoke-machine": typeof ApiConnectRevokeMachineRoute;
  "/marketplace/og/$pluginId": typeof MarketplaceOgPluginIdRoute;
  "/marketplace/v1/$": typeof MarketplaceV1SplatRoute;
  "/marketplace/v2/$": typeof MarketplaceV2SplatRoute;
  "/marketplace/author/$github": typeof MarketplaceAuthorGithubRoute;
  "/api/account/link/poll": typeof ApiAccountLinkPollRoute;
  "/api/account/link/start": typeof ApiAccountLinkStartRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/blog": typeof BlogRoute;
  "/changelog": typeof ChangelogRoute;
  "/dashboard": typeof DashboardRoute;
  "/link": typeof LinkRoute;
  "/marketplace": typeof MarketplaceRouteWithChildren;
  "/privacy": typeof PrivacyRoute;
  "/robots.txt": typeof RobotsDottxtRoute;
  "/sitemap.xml": typeof SitemapDotxmlRoute;
  "/.well-known/apple-app-site-association": typeof DotwellKnownAppleAppSiteAssociationRoute;
  "/.well-known/assetlinks.json": typeof DotwellKnownAssetlinksDotjsonRoute;
  "/api/subscribe": typeof ApiSubscribeRoute;
  "/blog/$slug": typeof BlogSlugRoute;
  "/download/linux": typeof DownloadLinuxRoute;
  "/download/macos": typeof DownloadMacosRoute;
  "/marketplace/$pluginId": typeof MarketplacePluginIdRoute;
  "/api/account/me": typeof ApiAccountMeRoute;
  "/api/auth/$": typeof ApiAuthSplatRoute;
  "/api/connect/machine-code": typeof ApiConnectMachineCodeRoute;
  "/api/connect/machine-code-lookup": typeof ApiConnectMachineCodeLookupRoute;
  "/api/connect/redeem": typeof ApiConnectRedeemRoute;
  "/api/connect/redeem-machine": typeof ApiConnectRedeemMachineRoute;
  "/api/connect/revoke-machine": typeof ApiConnectRevokeMachineRoute;
  "/marketplace/og/$pluginId": typeof MarketplaceOgPluginIdRoute;
  "/marketplace/v1/$": typeof MarketplaceV1SplatRoute;
  "/marketplace/v2/$": typeof MarketplaceV2SplatRoute;
  "/marketplace/author/$github": typeof MarketplaceAuthorGithubRoute;
  "/api/account/link/poll": typeof ApiAccountLinkPollRoute;
  "/api/account/link/start": typeof ApiAccountLinkStartRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/blog": typeof BlogRoute;
  "/changelog": typeof ChangelogRoute;
  "/dashboard": typeof DashboardRoute;
  "/link": typeof LinkRoute;
  "/marketplace_": typeof MarketplaceRouteWithChildren;
  "/privacy": typeof PrivacyRoute;
  "/robots.txt": typeof RobotsDottxtRoute;
  "/sitemap.xml": typeof SitemapDotxmlRoute;
  "/.well-known/apple-app-site-association": typeof DotwellKnownAppleAppSiteAssociationRoute;
  "/.well-known/assetlinks.json": typeof DotwellKnownAssetlinksDotjsonRoute;
  "/api/subscribe": typeof ApiSubscribeRoute;
  "/blog_/$slug": typeof BlogSlugRoute;
  "/download/linux": typeof DownloadLinuxRoute;
  "/download/macos": typeof DownloadMacosRoute;
  "/marketplace_/$pluginId": typeof MarketplacePluginIdRoute;
  "/api/account/me": typeof ApiAccountMeRoute;
  "/api/auth/$": typeof ApiAuthSplatRoute;
  "/api/connect/machine-code": typeof ApiConnectMachineCodeRoute;
  "/api/connect/machine-code-lookup": typeof ApiConnectMachineCodeLookupRoute;
  "/api/connect/redeem": typeof ApiConnectRedeemRoute;
  "/api/connect/redeem-machine": typeof ApiConnectRedeemMachineRoute;
  "/api/connect/revoke-machine": typeof ApiConnectRevokeMachineRoute;
  "/marketplace/og/$pluginId": typeof MarketplaceOgPluginIdRoute;
  "/marketplace/v1/$": typeof MarketplaceV1SplatRoute;
  "/marketplace/v2/$": typeof MarketplaceV2SplatRoute;
  "/marketplace_/author/$github": typeof MarketplaceAuthorGithubRoute;
  "/api/account/link/poll": typeof ApiAccountLinkPollRoute;
  "/api/account/link/start": typeof ApiAccountLinkStartRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/blog"
    | "/changelog"
    | "/dashboard"
    | "/link"
    | "/marketplace"
    | "/privacy"
    | "/robots.txt"
    | "/sitemap.xml"
    | "/.well-known/apple-app-site-association"
    | "/.well-known/assetlinks.json"
    | "/api/subscribe"
    | "/blog/$slug"
    | "/download/linux"
    | "/download/macos"
    | "/marketplace/$pluginId"
    | "/api/account/me"
    | "/api/auth/$"
    | "/api/connect/machine-code"
    | "/api/connect/machine-code-lookup"
    | "/api/connect/redeem"
    | "/api/connect/redeem-machine"
    | "/api/connect/revoke-machine"
    | "/marketplace/og/$pluginId"
    | "/marketplace/v1/$"
    | "/marketplace/v2/$"
    | "/marketplace/author/$github"
    | "/api/account/link/poll"
    | "/api/account/link/start";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | "/blog"
    | "/changelog"
    | "/dashboard"
    | "/link"
    | "/marketplace"
    | "/privacy"
    | "/robots.txt"
    | "/sitemap.xml"
    | "/.well-known/apple-app-site-association"
    | "/.well-known/assetlinks.json"
    | "/api/subscribe"
    | "/blog/$slug"
    | "/download/linux"
    | "/download/macos"
    | "/marketplace/$pluginId"
    | "/api/account/me"
    | "/api/auth/$"
    | "/api/connect/machine-code"
    | "/api/connect/machine-code-lookup"
    | "/api/connect/redeem"
    | "/api/connect/redeem-machine"
    | "/api/connect/revoke-machine"
    | "/marketplace/og/$pluginId"
    | "/marketplace/v1/$"
    | "/marketplace/v2/$"
    | "/marketplace/author/$github"
    | "/api/account/link/poll"
    | "/api/account/link/start";
  id:
    | "__root__"
    | "/"
    | "/blog"
    | "/changelog"
    | "/dashboard"
    | "/link"
    | "/marketplace_"
    | "/privacy"
    | "/robots.txt"
    | "/sitemap.xml"
    | "/.well-known/apple-app-site-association"
    | "/.well-known/assetlinks.json"
    | "/api/subscribe"
    | "/blog_/$slug"
    | "/download/linux"
    | "/download/macos"
    | "/marketplace_/$pluginId"
    | "/api/account/me"
    | "/api/auth/$"
    | "/api/connect/machine-code"
    | "/api/connect/machine-code-lookup"
    | "/api/connect/redeem"
    | "/api/connect/redeem-machine"
    | "/api/connect/revoke-machine"
    | "/marketplace/og/$pluginId"
    | "/marketplace/v1/$"
    | "/marketplace/v2/$"
    | "/marketplace_/author/$github"
    | "/api/account/link/poll"
    | "/api/account/link/start";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  BlogRoute: typeof BlogRoute;
  ChangelogRoute: typeof ChangelogRoute;
  DashboardRoute: typeof DashboardRoute;
  LinkRoute: typeof LinkRoute;
  MarketplaceRoute: typeof MarketplaceRouteWithChildren;
  PrivacyRoute: typeof PrivacyRoute;
  RobotsDottxtRoute: typeof RobotsDottxtRoute;
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute;
  DotwellKnownAppleAppSiteAssociationRoute: typeof DotwellKnownAppleAppSiteAssociationRoute;
  DotwellKnownAssetlinksDotjsonRoute: typeof DotwellKnownAssetlinksDotjsonRoute;
  ApiSubscribeRoute: typeof ApiSubscribeRoute;
  BlogSlugRoute: typeof BlogSlugRoute;
  DownloadLinuxRoute: typeof DownloadLinuxRoute;
  DownloadMacosRoute: typeof DownloadMacosRoute;
  ApiAccountMeRoute: typeof ApiAccountMeRoute;
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute;
  ApiConnectMachineCodeRoute: typeof ApiConnectMachineCodeRoute;
  ApiConnectMachineCodeLookupRoute: typeof ApiConnectMachineCodeLookupRoute;
  ApiConnectRedeemRoute: typeof ApiConnectRedeemRoute;
  ApiConnectRedeemMachineRoute: typeof ApiConnectRedeemMachineRoute;
  ApiConnectRevokeMachineRoute: typeof ApiConnectRevokeMachineRoute;
  MarketplaceOgPluginIdRoute: typeof MarketplaceOgPluginIdRoute;
  MarketplaceV1SplatRoute: typeof MarketplaceV1SplatRoute;
  MarketplaceV2SplatRoute: typeof MarketplaceV2SplatRoute;
  ApiAccountLinkPollRoute: typeof ApiAccountLinkPollRoute;
  ApiAccountLinkStartRoute: typeof ApiAccountLinkStartRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/sitemap.xml": {
      id: "/sitemap.xml";
      path: "/sitemap.xml";
      fullPath: "/sitemap.xml";
      preLoaderRoute: typeof SitemapDotxmlRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/robots.txt": {
      id: "/robots.txt";
      path: "/robots.txt";
      fullPath: "/robots.txt";
      preLoaderRoute: typeof RobotsDottxtRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/privacy": {
      id: "/privacy";
      path: "/privacy";
      fullPath: "/privacy";
      preLoaderRoute: typeof PrivacyRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/marketplace_": {
      id: "/marketplace_";
      path: "/marketplace";
      fullPath: "/marketplace";
      preLoaderRoute: typeof MarketplaceRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/link": {
      id: "/link";
      path: "/link";
      fullPath: "/link";
      preLoaderRoute: typeof LinkRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/dashboard": {
      id: "/dashboard";
      path: "/dashboard";
      fullPath: "/dashboard";
      preLoaderRoute: typeof DashboardRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/changelog": {
      id: "/changelog";
      path: "/changelog";
      fullPath: "/changelog";
      preLoaderRoute: typeof ChangelogRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/blog": {
      id: "/blog";
      path: "/blog";
      fullPath: "/blog";
      preLoaderRoute: typeof BlogRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/marketplace_/$pluginId": {
      id: "/marketplace_/$pluginId";
      path: "/$pluginId";
      fullPath: "/marketplace/$pluginId";
      preLoaderRoute: typeof MarketplacePluginIdRouteImport;
      parentRoute: typeof MarketplaceRoute;
    };
    "/download/macos": {
      id: "/download/macos";
      path: "/download/macos";
      fullPath: "/download/macos";
      preLoaderRoute: typeof DownloadMacosRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/download/linux": {
      id: "/download/linux";
      path: "/download/linux";
      fullPath: "/download/linux";
      preLoaderRoute: typeof DownloadLinuxRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/blog_/$slug": {
      id: "/blog_/$slug";
      path: "/blog/$slug";
      fullPath: "/blog/$slug";
      preLoaderRoute: typeof BlogSlugRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/api/subscribe": {
      id: "/api/subscribe";
      path: "/api/subscribe";
      fullPath: "/api/subscribe";
      preLoaderRoute: typeof ApiSubscribeRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/.well-known/assetlinks.json": {
      id: "/.well-known/assetlinks.json";
      path: "/.well-known/assetlinks.json";
      fullPath: "/.well-known/assetlinks.json";
      preLoaderRoute: typeof DotwellKnownAssetlinksDotjsonRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/.well-known/apple-app-site-association": {
      id: "/.well-known/apple-app-site-association";
      path: "/.well-known/apple-app-site-association";
      fullPath: "/.well-known/apple-app-site-association";
      preLoaderRoute: typeof DotwellKnownAppleAppSiteAssociationRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/marketplace_/author/$github": {
      id: "/marketplace_/author/$github";
      path: "/author/$github";
      fullPath: "/marketplace/author/$github";
      preLoaderRoute: typeof MarketplaceAuthorGithubRouteImport;
      parentRoute: typeof MarketplaceRoute;
    };
    "/marketplace/v2/$": {
      id: "/marketplace/v2/$";
      path: "/marketplace/v2/$";
      fullPath: "/marketplace/v2/$";
      preLoaderRoute: typeof MarketplaceV2SplatRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/marketplace/v1/$": {
      id: "/marketplace/v1/$";
      path: "/marketplace/v1/$";
      fullPath: "/marketplace/v1/$";
      preLoaderRoute: typeof MarketplaceV1SplatRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/marketplace/og/$pluginId": {
      id: "/marketplace/og/$pluginId";
      path: "/marketplace/og/$pluginId";
      fullPath: "/marketplace/og/$pluginId";
      preLoaderRoute: typeof MarketplaceOgPluginIdRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/api/connect/revoke-machine": {
      id: "/api/connect/revoke-machine";
      path: "/api/connect/revoke-machine";
      fullPath: "/api/connect/revoke-machine";
      preLoaderRoute: typeof ApiConnectRevokeMachineRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/api/connect/redeem-machine": {
      id: "/api/connect/redeem-machine";
      path: "/api/connect/redeem-machine";
      fullPath: "/api/connect/redeem-machine";
      preLoaderRoute: typeof ApiConnectRedeemMachineRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/api/connect/redeem": {
      id: "/api/connect/redeem";
      path: "/api/connect/redeem";
      fullPath: "/api/connect/redeem";
      preLoaderRoute: typeof ApiConnectRedeemRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/api/connect/machine-code-lookup": {
      id: "/api/connect/machine-code-lookup";
      path: "/api/connect/machine-code-lookup";
      fullPath: "/api/connect/machine-code-lookup";
      preLoaderRoute: typeof ApiConnectMachineCodeLookupRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/api/connect/machine-code": {
      id: "/api/connect/machine-code";
      path: "/api/connect/machine-code";
      fullPath: "/api/connect/machine-code";
      preLoaderRoute: typeof ApiConnectMachineCodeRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/api/auth/$": {
      id: "/api/auth/$";
      path: "/api/auth/$";
      fullPath: "/api/auth/$";
      preLoaderRoute: typeof ApiAuthSplatRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/api/account/me": {
      id: "/api/account/me";
      path: "/api/account/me";
      fullPath: "/api/account/me";
      preLoaderRoute: typeof ApiAccountMeRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/api/account/link/start": {
      id: "/api/account/link/start";
      path: "/api/account/link/start";
      fullPath: "/api/account/link/start";
      preLoaderRoute: typeof ApiAccountLinkStartRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/api/account/link/poll": {
      id: "/api/account/link/poll";
      path: "/api/account/link/poll";
      fullPath: "/api/account/link/poll";
      preLoaderRoute: typeof ApiAccountLinkPollRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

interface MarketplaceRouteChildren {
  MarketplacePluginIdRoute: typeof MarketplacePluginIdRoute;
  MarketplaceAuthorGithubRoute: typeof MarketplaceAuthorGithubRoute;
}

const MarketplaceRouteChildren: MarketplaceRouteChildren = {
  MarketplacePluginIdRoute: MarketplacePluginIdRoute,
  MarketplaceAuthorGithubRoute: MarketplaceAuthorGithubRoute,
};

const MarketplaceRouteWithChildren = MarketplaceRoute._addFileChildren(
  MarketplaceRouteChildren,
);

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlogRoute: BlogRoute,
  ChangelogRoute: ChangelogRoute,
  DashboardRoute: DashboardRoute,
  LinkRoute: LinkRoute,
  MarketplaceRoute: MarketplaceRouteWithChildren,
  PrivacyRoute: PrivacyRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  DotwellKnownAppleAppSiteAssociationRoute:
    DotwellKnownAppleAppSiteAssociationRoute,
  DotwellKnownAssetlinksDotjsonRoute: DotwellKnownAssetlinksDotjsonRoute,
  ApiSubscribeRoute: ApiSubscribeRoute,
  BlogSlugRoute: BlogSlugRoute,
  DownloadLinuxRoute: DownloadLinuxRoute,
  DownloadMacosRoute: DownloadMacosRoute,
  ApiAccountMeRoute: ApiAccountMeRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiConnectMachineCodeRoute: ApiConnectMachineCodeRoute,
  ApiConnectMachineCodeLookupRoute: ApiConnectMachineCodeLookupRoute,
  ApiConnectRedeemRoute: ApiConnectRedeemRoute,
  ApiConnectRedeemMachineRoute: ApiConnectRedeemMachineRoute,
  ApiConnectRevokeMachineRoute: ApiConnectRevokeMachineRoute,
  MarketplaceOgPluginIdRoute: MarketplaceOgPluginIdRoute,
  MarketplaceV1SplatRoute: MarketplaceV1SplatRoute,
  MarketplaceV2SplatRoute: MarketplaceV2SplatRoute,
  ApiAccountLinkPollRoute: ApiAccountLinkPollRoute,
  ApiAccountLinkStartRoute: ApiAccountLinkStartRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

import type { getRouter } from "./router.tsx";
import type { createStart } from "@tanstack/react-start";
declare module "@tanstack/react-start" {
  interface Register {
    ssr: true;
    router: Awaited<ReturnType<typeof getRouter>>;
  }
}
