import { type HostDaemonRpcCommand } from "@bb/host-daemon-contract";

const hostCommandWakePolicy = {
  "server_move.abort": "never",
  "server_move.activate": "never",
  "server_move.delete_old_copy": "never",
  "server_move.inspect": "never",
  "server_move.prepare": "never",
  "server_move.probe": "never",
  "thread.rewind.discard": "never",
  "thread.rewind.prepare": "work",
  "thread.start": "work",
  "turn.submit": "work",
  "thread.stop": "never",
  "thread.storage.delete": "never",
  "thread.goal.clear": "never",
  "thread.plan.cancel": "never",
  "thread.rename": "never",
  "thread.archive": "never",
  "thread.unarchive": "never",
  "interactive.resolve": "never",
  "environment.attach": "work",
  "project.clone": "work",
  "environment.attach.cancel": "never",
  "workspace.commit": "work",
  "workspace.pull_request_action": "work",
  "desktop.browser.list_instances": "work",
  "desktop.browser.list_tabs": "work",
  "desktop.browser.create_tab": "work",
  "desktop.browser.reveal_tab": "work",
  "desktop.browser.close_tab": "never",
  "desktop.browser.capture_tab": "work",
  "desktop.browser.acquire_control": "work",
  "desktop.browser.open_connection": "work",
  "desktop.browser.release_control": "never",
  "desktop.browser.list_import_sources": "work",
  "desktop.browser.import_cookies": "work",
  "host.list_files": "work",
  "host.list_paths": "work",
  "host.mkdir": "work",
  "host.move_path": "work",
  "host.remove_path": "work",
  "host.browse_directory": "work",
  "host.paths_exist": "work",
  "project.inspect": "work",
  "project.clone_default_path": "work",
  "host.pick_folder": "work",
  "environment.hook.run": "work",
  "environment.hook.cancel": "never",
  "plugin.host.call": "work",
  "plugin.host.cancel": "never",
  "plugin.host.dispose": "never",
  "connect-tunnel.ensure-identity": "work",
  "host.list_commands": "work",
  "host.list_skills": "work",
  "host.delete_skill": "work",
  "host.write_skill": "work",
  "host.install_global_skills": "work",
  "host.global_skills_status": "work",
  "host.inspect_git_source": "work",
  "host.list_branch_options": "work",
  "host.read_file": "work",
  "host.read_file_chunk": "work",
  "host.read_file_relative": "work",
  "host.write_file": "work",
  "provider.list_models": "work",
  "provider.health": "work",
  "provider.installation.status": "work",
  "provider.installation.run": "work",
  "provider.usage": "work",
  "workspace.status": "work",
  "workspace.diff": "work",
  "workspace.diffFiles": "work",
  "workspace.diffPatch": "work",
  "workspace.pull_request": "work",
} satisfies Record<HostDaemonRpcCommand["type"], "never" | "work">;

export function hostCommandMayWake(command: HostDaemonRpcCommand): boolean {
  if (command.type === "environment.hook.run" && command.kind === "teardown") {
    return false;
  }
  return hostCommandWakePolicy[command.type] === "work";
}
