export interface PluginSurface {
  id: string;
  title: string;
  summary: string;
  bullets: string[];
  tagline?: string;
  apiSymbols: string[];
  firstParty?: string[];
  experimental?: boolean;
}

export interface SurfaceGroup {
  id:
    | "app-shell"
    | "command-palette"
    | "composer"
    | "home"
    | "settings"
    | "extensions"
    | "headless";
  title: string;
  blurb: string;
  fixtureKind: "spatial" | "capability-grid";
  surfaces: PluginSurface[];
  sections?: readonly {
    title: string;
    surfaceIds: readonly string[];
  }[];
}

export type FixtureResponsiveStrategy = "scale-together" | "reflow";

export function fixtureResponsiveStrategy(
  group: Pick<SurfaceGroup, "fixtureKind">,
): FixtureResponsiveStrategy {
  return group.fixtureKind === "spatial" ? "scale-together" : "reflow";
}

export const SURFACE_GROUPS: SurfaceGroup[] = [
  {
    id: "app-shell",
    title: "The bb app window",
    fixtureKind: "spatial",
    blurb:
      "The main bb window, containing the sidebar, the conversation, and the side panel. A plugin can add rows, controls, panel tabs, and message content to the numbered regions.",
    surfaces: [
      {
        id: "nav-panel",
        title: "Full-page panels",
        summary:
          "Add a navigation rail destination that opens a full page your plugin renders. With this, a plugin can:",
        bullets: [
          "Build a whole page, such as a dashboard, a board, or an inbox",
          "Give the page a URL that can be shared and works with back and forward",
          "Add fixed tabs beside Browser and Terminal, and open terminals it started in any folder",
        ],
        apiSymbols: [
          "PluginNavPanelRegistration",
          "PluginNavPanelProps",
          "PluginFixedTabRegistration",
          "PluginFixedTabDeclaration",
          "ExperimentalPluginFixedTabReference",
          "ExperimentalFixedTabTargetContract",
          "experimental_useAppPanel",
          "ExperimentalAppPanel",
          "ExperimentalOpenFixedTabOptions",
          "experimental_useFixedTabTarget",
          "ExperimentalFixedTabTargetState",
          "useBbContext",
          "useBbNavigate",
          "BbNavigate.toPluginPanel",
          "BbNavigate.experimental_openTerminal",
        ],
        firstParty: ["Automations", "Docs", "GitHub", "Tasks", "Theme Preview"],
      },
      {
        id: "thread-row-status",
        title: "Thread row status",
        summary:
          "Add a small status icon to a thread's row in the sidebar. With this, a plugin can:",
        bullets: [
          "Show that the plugin is working on a thread, with a shimmering icon",
          "Settle the icon to succeeded or failed when the work ends",
          "Set it from an [app-wide script](content-scripts), which bb cleans up after",
        ],
        apiSymbols: [
          "PluginComposerThreadRowStatus",
          "PluginContentScriptContext",
        ],
        experimental: true,
      },
      {
        id: "thread-list",
        title: "The thread list",
        summary:
          "Replace the sidebar's thread list with one your plugin renders. With this, a plugin can:",
        bullets: [
          "Group, sort, and draw every row your own way, or only add entries to each thread's actions menu",
          "Read live threads, sections, projects, run status, and pull-request checks",
          "Use optimistic SDK writes and bb's actions to move, pin, rename, restore, archive, and split threads",
          "Keep bb's New thread button, search, and footer around it",
        ],
        apiSymbols: [
          "PluginThreadListRegistration",
          "PluginThreadListProps",
          "experimental_useSidebarThreads",
          "PluginSidebarThreadsState.experimental_archived",
          "PluginSidebarThreadsState.experimental_hosts",
          "PluginSidebarThreadsState",
          "PluginSidebarThread",
          "PluginSidebarSection",
          "experimental_useSidebarThreadActions",
          "PluginSidebarThreadActions",
          "ExperimentalThreadMenuActionRegistration",
          "ExperimentalThreadMenuActionContext",
          "experimental_useThreadMenuActions",
          "ExperimentalThreadMenuAction",
          "PluginSidebarThreadActions.experimental_archiveEnvironmentThreads",
          "PluginSidebarThreadActions.openNewThread",
          "PluginSidebarThreadActions.openNewThread.experimental_placement",
          "experimental_useSidebarThreadPullRequest",
          "PluginSidebarThreadPullRequestState",
          "PluginSidebarPullRequest.experimental_autoMerge",
          "PluginSidebarPullRequest.experimental_inMergeQueue",
          "PluginSidebarPullRequest.experimental_checks",
          "PluginSidebarPullRequest.experimental_review",
          "PluginSidebarPullRequest.experimental_mergeability",
          "experimental_useSidebarThreadSplit",
          "PluginSidebarThreadSplit",
          "useSidebarThreadDraft",
          "PluginSidebarThreadDraftState",
          "useSidebarThreadDraftIds",
          "useSidebarThreadRowStatus",
          "useSidebarThreadRowStatuses",
          "PluginSidebarThreadRowStatus",
          "useSidebarSplitLayout",
          "PluginSidebarSplitLayout",
          "useSidebarThreadShortcut",
          "PluginSidebarThreadShortcut",
          "ThreadTitle",
          "PluginThreadTitleProps",
          "useEnvironmentProviders",
          "PluginEnvironmentProvidersState",
          "useSdk",
          "PluginBrowserBbSdk",
          "experimental_usePluginId",
        ],
        firstParty: ["Thread list"],
        experimental: true,
      },
      {
        id: "sidebar-footer",
        title: "Sidebar footer items",
        summary:
          "Add an icon to the bottom of bb's sidebar. With this, a plugin can:",
        bullets: [
          "Run an action, or open a small panel above the footer",
          "Show quick status, such as usage limits, without leaving the thread",
          "Follow the user's order and visibility choices in Appearance",
        ],
        apiSymbols: [
          "ExperimentalSidebarFooter",
          "ExperimentalSidebarFooterItemBase",
          "ExperimentalSidebarFooterItemRegistration",
          "ExperimentalSidebarFooterActionRegistration",
          "ExperimentalSidebarFooterActionContext",
          "ExperimentalSidebarFooterDisclosureRegistration",
          "ExperimentalSidebarFooterDisclosureProps",
          "ExperimentalSidebarFooterDisclosureController",
          "PluginSidebarFooterActionRegistration",
          "PluginSidebarFooterActionProps",
        ],
        firstParty: ["Provider usage"],
        experimental: true,
      },
      {
        id: "thread-header",
        title: "Thread header controls",
        summary:
          "Add a control to the header of an open thread. With this, a plugin can:",
        bullets: [
          "Show live state for the thread on screen, not just a static button",
          "Sit in the same row as bb's own header controls",
        ],
        apiSymbols: [
          "PluginThreadHeaderActionRegistration",
          "PluginThreadHeaderActionProps",
        ],
        experimental: true,
      },
      {
        id: "timeline-renderers",
        title: "Timeline entry content",
        summary:
          "Add rich detail to the timeline entries your plugin creates. With this, a plugin can:",
        bullets: [
          "Draw custom content under each entry while bb keeps its header and controls",
          "Fall back to bb's default view if the plugin is off or crashes",
        ],
        apiSymbols: [
          "PluginTimelineRendererRegistration",
          "PluginTimelineRendererProps",
        ],
        experimental: true,
      },
      {
        id: "message-directives",
        title: "Rich message embeds",
        summary:
          "Add live components to an agent's reply. With this, a plugin can:",
        bullets: [
          "Let an agent write `::name` to place your component in its message",
          "Show charts, task lists, or previews inline in the conversation",
          "Open workspace files when someone clicks the embed",
        ],
        apiSymbols: [
          "PluginMessageDirectiveRegistration",
          "PluginMessageDirectiveProps",
          "PluginMessageDirectiveOpenWorkspaceFile",
        ],
        firstParty: [
          "Browser Automation",
          "Docs",
          "Inline visualizations",
          "Tasks",
          "Workflows",
        ],
      },
      {
        id: "message-actions",
        title: "Message actions",
        summary:
          "Add an action to messages in a thread. With this, a plugin can:",
        bullets: [
          "Appear under messages on hover, or on text selected in a reply, in the main timeline only",
          "Receive the message with the sequence its link uses, or the selected text",
          "Open a [side-panel tab](thread-panel) or write into the composer with the result",
        ],
        apiSymbols: [
          "PluginMessageActionRegistration",
          "PluginMessageActionContext",
          "ThreadChatMessageReference",
        ],
        firstParty: ["Side chat"],
      },
      {
        id: "pending-interaction",
        title: "In-thread forms",
        summary:
          "Add a form that asks the person a question and returns the answer to the agent. With this, a plugin can:",
        bullets: [
          "Replace the prompt box with your form, even after the turn has ended",
          "Return the answer or cancellation to the agent and keep a record in the thread",
          "Show bb's answer shortcuts and respond when the person presses one",
          "Dictate editable answers and wait for voice input before navigating or submitting",
        ],
        apiSymbols: [
          "PluginUi",
          "PluginInteractionRequest",
          "PluginInteractionDescription",
          "PluginRowPresentation",
          "PluginPendingInteractionRegistration",
          "experimental_useQuestionFormHost",
          "PluginPendingInteractionProps",
          "PluginPendingInteractionView",
        ],
        firstParty: ["Ask User Question", "Pi provider", "Secrets"],
      },
      {
        id: "code-renderers",
        title: "Code & diff renderers",
        summary:
          "Replace bb's code or diff viewer everywhere it appears. With this, a plugin can:",
        bullets: [
          "Restyle file previews, timeline diffs, and plugin pages in one place",
          "Replace code and diffs independently",
          "Hand any render back to bb, which also takes over if the plugin crashes",
        ],
        apiSymbols: [
          "PluginSourceCodeRendererRegistration",
          "PluginSourceCodeRendererProps",
          "PluginDiffRendererRegistration",
          "PluginDiffRendererProps",
        ],
        experimental: true,
      },
      {
        id: "browser-toolbar",
        title: "Browser toolbar controls",
        summary:
          "Add a control to the toolbar of each Browser tab. With this, a plugin can:",
        bullets: [
          "Act on the page the person is looking at, with its URL and thread",
          "Run scripts in the page on desktop and get results back",
        ],
        apiSymbols: [
          "ExperimentalPluginBrowserToolbarActionRegistration",
          "ExperimentalPluginBrowserToolbarActionProps",
          "ExperimentalPluginBrowserPage",
          "ExperimentalPluginBrowserPageEvaluateOptions",
          "ExperimentalPluginBrowserPageWorld",
        ],
        firstParty: ["Agent Annotations"],
        experimental: true,
      },
      {
        id: "thread-panel",
        title: "Thread side-panel tabs",
        summary:
          "Add a tab to the side panel next to a thread. With this, a plugin can:",
        bullets: [
          "Show plugin content alongside the conversation",
          "Know which thread it was opened from",
          "Open from a [message action](message-actions), the side panel's + button, or plugin code",
        ],
        apiSymbols: [
          "PluginThreadPanelActionRegistration",
          "BbNavigate.openThreadPanel",
          "PluginThreadPanelProps",
          "PluginThreadPanelActionContext",
        ],
        firstParty: ["Docs", "GitHub", "Side chat", "Tasks", "Workflows"],
      },
      {
        id: "file-opener",
        title: "File viewers & editors",
        summary:
          "Add a viewer or editor for the file types you choose. With this, a plugin can:",
        bullets: [
          "Open files such as `.csv` or `.excalidraw` in your own view",
          "Jump to the linked lines when someone opens a file reference",
          "Hand individual files back to bb's built-in preview",
        ],
        apiSymbols: [
          "PluginFileOpenerRegistration",
          "PluginFileOpenerProps",
          "PluginFileOpenerSource",
        ],
        firstParty: ["Docs", "File Editor", "PDF preview"],
      },
      {
        id: "app-overlay",
        title: "App-wide overlays",
        summary:
          "Add a floating widget that stays on screen across bb. With this, a plugin can:",
        bullets: [
          "Show persistent UI, such as a timer or a status badge, on every page",
          "Control its own position and visibility, and fail without affecting the rest of the app",
          "Open a new-thread composer, with its own project and draft, in a pane beside the focused one",
          "Handle bb's own New thread buttons and command, for example to open them in a split pane",
        ],
        apiSymbols: [
          "ExperimentalAppOverlayRegistration",
          "ExperimentalAppOverlayProps",
          "experimental_useSplitPanes",
          "ExperimentalSplitPanes",
          "ExperimentalSplitPaneNewThreadOptions",
          "ExperimentalSplitPaneOpenResult",
          "experimental_useNewThreadHandler",
          "ExperimentalNewThreadHandler",
          "ExperimentalNewThreadRequest",
        ],
        firstParty: ["Browser Automation", "Push notifications"],
        experimental: true,
      },
      {
        id: "content-scripts",
        title: "App-wide scripts",
        summary:
          "Run code in every bb window, without a UI of its own. With this, a plugin can:",
        bullets: [
          "Add app-wide behavior, such as a keyboard shortcut",
          "Set a [thread row status](thread-row-status) on any thread",
          "Clean up automatically when the window reloads",
        ],
        apiSymbols: [
          "PluginContentScriptRegistration",
          "PluginContentScriptContext",
        ],
        firstParty: ["Provider usage"],
      },
    ],
  },
  {
    id: "command-palette",
    title: "Command palette",
    fixtureKind: "spatial",
    blurb:
      "bb's searchable command menu. A plugin can add actions that match, rank, and run alongside bb's own commands.",
    surfaces: [
      {
        id: "command-palette-actions",
        title: "Command palette actions",
        summary:
          "Add commands to bb's command palette. With this, a plugin can:",
        bullets: [
          "Run plugin actions from the palette or a keyboard shortcut",
          "Suggest a default shortcut that people can rebind",
          "Show a command only when the current thread or project fits",
          "Open a plugin panel for the focused thread or New thread screen",
        ],
        apiSymbols: [
          "PluginAppBuilder.commands",
          "PluginAppCommands",
          "PluginCommandRegistration",
          "PluginCommandContext",
          "PluginCommandShortcut",
        ],
        firstParty: ["File Editor"],
      },
    ],
  },
  {
    id: "composer",
    title: "The composer",
    fixtureKind: "spatial",
    blurb:
      "The prompt box used to start a thread and to reply inside one. A plugin can add banners, menu entries, and action buttons to it, answer mention searches, highlight the draft prompt, and supply the agent that runs the message.",
    surfaces: [
      {
        id: "composer-banners",
        title: "Banners",
        summary: "Add a banner above the prompt box. With this, a plugin can:",
        bullets: [
          "Warn or inform before someone sends, such as a rate limit or a retry",
          "Show only on new threads, open threads, or queued messages",
        ],
        apiSymbols: ["ComposerCustomization", "PluginComposerScope"],
        firstParty: ["Send later", "Workflows"],
      },
      {
        id: "composer-state",
        title: "Draft prompt state & locking",
        summary:
          "Use the draft prompt from plugin code. With this, a plugin can:",
        bullets: [
          "Read the draft's text, @-mentions, and attachments",
          "Insert or rewrite text, @-mentions, and thread pills in one step",
          "Lock the prompt box while the plugin works, then release it",
          "Write into any prompt box on screen from a panel or page",
        ],
        apiSymbols: [
          "useComposer",
          "useComposers",
          "PluginComposerApi",
          "ComposerDraft",
          "ComposerDraftReplacement",
          "ComposerAttachment",
          "PluginComposerApi.replace",
          "ComposerDraftSnapshot",
          "PluginComposerApi.insert",
          "ComposerMention",
        ],
        firstParty: ["Agent Annotations", "Docs", "Send later", "Workflows"],
      },
      {
        id: "mention-provider",
        title: "Mentions",
        summary:
          "Add items to the menu that opens when someone types @ or another trigger. With this, a plugin can:",
        bullets: [
          "Search the plugin's own data as the person types",
          "Claim its own trigger, such as # or $",
          "Turn a pick into a chip whose content reaches the agent on send",
        ],
        apiSymbols: [
          "PluginMentionProviderRegistration",
          "PluginMentionSearchContext",
          "PluginMentionItem",
        ],
        firstParty: ["Agent Annotations", "Docs", "GitHub", "Tasks"],
      },
      {
        id: "composer-rich-text",
        title: "Draft prompt highlighting",
        summary:
          "Add highlighting to text as someone types a prompt. With this, a plugin can:",
        bullets: [
          "Highlight matches such as ticket numbers or TODOs without changing the text",
          "Respond after a message is sent or queued",
        ],
        apiSymbols: [
          "ComposerRichTextSpec",
          "PluginComposerApi.replace",
          "PluginComposerApi.onSubmitted",
        ],
      },
      {
        id: "composer-plus-menu",
        title: "The + and send menus",
        summary:
          "Add rows to the + menu or the menu beside the send button. With this, a plugin can:",
        bullets: [
          "Offer actions such as templates from the prompt box",
          "Send the draft later, keeping its attachments and mentions",
          "Attach plugin data to a send for its [dispatch hook](dispatch-hook)",
        ],
        apiSymbols: [
          "ComposerPlusMenuItem",
          "ComposerSendMenuItem",
          "ComposerSubmitOptions",
        ],
        firstParty: ["Automations", "BB guide", "Drafts", "Send later"],
      },
      {
        id: "provider-picker",
        title: "Agent providers",
        summary:
          "Provide an agent people can pick in bb's model picker. With this, a plugin can:",
        bullets: [
          "Bring any CLI agent into bb, with its own models and icon",
          "Run every thread started with it through a bridge the plugin ships",
          "Report context usage, service tiers, and install status",
        ],
        apiSymbols: [
          "contextSnapshotSchema",
          "ContextSnapshot",
          "ContextCategory",
          "ContextEntry",
          "PluginProviderDeclaration",
          "AvailableModel",
          "ModelServiceTier",
          "providerInstallationStatusParamsSchema",
          "ProviderInstallationStatusParams",
          "PluginProviderIconRegistration",
          "experimental_useProviders",
          "PluginProvidersState",
          "ExperimentalPluginProviderEnvContext",
          "ExperimentalPluginProviderEnvEntry",
          "ExperimentalPluginProviderEnvHealthContext",
          "ExperimentalPluginProviderEnvHealth",
          "experimental_spawnPortableProcess",
          "experimental_killPortableProcess",
          "PluginProviders",
        ],
        firstParty: [
          "ACP providers",
          "Claude Code provider",
          "Codex provider",
          "Pi provider",
        ],
        experimental: true,
      },
      {
        id: "composer-actions",
        title: "Inline actions",
        summary:
          "Add a button inside the prompt box, beside voice and send. With this, a plugin can:",
        bullets: [
          "Rewrite the draft, for example to rephrase it or insert a template",
          "Open a popup anchored to the prompt box",
          "Run from a keyboard shortcut people can rebind",
          "Preview a live transcript at the caret, transcribing bb's own voice input your own way",
        ],
        apiSymbols: [
          "PluginComposerApi",
          "PluginComposerApi.insert",
          "ComposerInsertPart",
          "ComposerInsertOptions",
          "ComposerCustomization.experimental_popups",
          "ExperimentalComposerPopupRegistration",
          "PluginComposerApi.experimental_openPopup",
          "PluginComposerApi.experimental_closePopup",
          "PluginAppComposer.experimental_registerCommand",
          "ExperimentalComposerCommandRegistration",
          "PluginComposerApi.setSelection",
          "PluginComposerApi.selection",
          "ComposerSelection",
          "PluginComposerApi.experimental_beginProvisionalText",
          "ExperimentalComposerProvisionalText",
          "ExperimentalComposerVoiceInput",
          "ExperimentalComposerVoiceSession",
          "ExperimentalComposerVoiceRecording",
        ],
      },
    ],
  },
  {
    id: "home",
    title: "Home page",
    fixtureKind: "spatial",
    blurb:
      "The screen bb opens on, holding the new-thread composer and a side panel. A plugin can add a section below the composer, and an action in that panel that opens its own tab.",
    surfaces: [
      {
        id: "homepage-section",
        title: "Home-screen sections",
        summary: "Add a section to bb's home page. With this, a plugin can:",
        bullets: [
          "Show shortcuts, pinned work, or recent activity before any thread exists",
          "Span the full width below the composer on desktop",
        ],
        apiSymbols: [
          "PluginHomepageSectionRegistration",
          "PluginHomepageSectionProps",
        ],
      },
      {
        id: "new-thread-panel",
        title: "New-thread side panel",
        summary:
          "Add a side-panel tab to the new-thread screen. With this, a plugin can:",
        bullets: [
          "Help people set up work while they write the first prompt",
          "Use the project selected in the prompt box",
        ],
        apiSymbols: [
          "PluginNewThreadPanelActionRegistration",
          "PluginNewThreadPanelProps",
        ],
        experimental: true,
      },
    ],
  },
  {
    id: "settings",
    title: "Plugin settings page",
    fixtureKind: "spatial",
    blurb:
      "The settings page bb creates for every installed plugin. A plugin can declare fields for bb to render and add its own section below them.",
    surfaces: [
      {
        id: "declarative-settings",
        title: "Settings fields",
        summary:
          "Add settings fields to the plugin's settings page without writing UI. With this, a plugin can:",
        bullets: [
          "Declare text, number, toggle, choice, or project fields as data",
          "Get validation and autosave without extra code",
          "Keep secret values on the server, never sent to the browser",
        ],
        apiSymbols: [
          "PluginSettings",
          "PluginSettingsHandle",
          "PluginSettingDescriptor",
          "PluginSettingsState",
          "useSettings",
          "PluginSettingsValues",
        ],
        firstParty: [
          "ACP providers",
          "bb connect",
          "BB guide",
          "Claude Code provider",
          "Codex provider",
          "Custom instructions",
          "GitHub",
          "Modal Sandbox [Experimental]",
          "Provider retry",
          "Push notifications",
          "Workflows",
        ],
      },
      {
        id: "settings-section",
        title: "Custom settings section",
        summary:
          "Add your own section to the plugin's settings page. With this, a plugin can:",
        bullets: [
          "Show anything that isn't a form field, such as a connect-account button",
          "Sit below the [generated fields](declarative-settings) under a heading bb renders",
        ],
        apiSymbols: [
          "PluginSettingsSectionRegistration.experimental_page",
          "PluginSettingsSectionRegistration",
          "PluginSettingsSectionProps",
        ],
        firstParty: [
          "Account Pooler [Experimental]",
          "bb account",
          "bb connect",
          "Concurrency limit",
          "Keep Awake",
          "Memory",
          "Modal Sandbox [Experimental]",
          "Provider usage",
          "Push notifications",
        ],
      },
    ],
  },
  {
    id: "extensions",
    title: "Plugin page",
    fixtureKind: "spatial",
    blurb:
      "The page bb shows for an installed plugin under Plugins: what it is, what it registers, and whether it is healthy. A plugin can report that it needs configuring, and bb says so at the top of this page.",
    surfaces: [
      {
        id: "plugin-status",
        title: "Configuration status",
        summary:
          "Add a needs-configuration warning to the plugin's page. With this, a plugin can:",
        bullets: [
          "Tell people what's missing instead of failing silently",
          "Send them to Settings, then reload after they save",
        ],
        apiSymbols: ["PluginStatusApi"],
        firstParty: [
          "Account Pooler [Experimental]",
          "GitHub",
          "Modal Sandbox [Experimental]",
          "Workflows",
        ],
      },
    ],
  },
  {
    id: "headless",
    title: "Plugin backend",
    fixtureKind: "capability-grid",
    blurb: "The parts of the plugin API with no interface of their own.",
    sections: [
      {
        title: "Commands & agent capabilities",
        surfaceIds: ["cli", "agent-tools"],
      },
      {
        title: "Running & reacting",
        surfaceIds: [
          "background",
          "wire",
          "thread-events",
          "dispatch-hook",
          "environment-providers",
          "machine-providers",
          "server-access",
          "host-workers",
          "provider-bridges",
        ],
      },
      {
        title: "Data & platform",
        surfaceIds: [
          "storage",
          "bb-sdk",
          "thread-plugin-metadata",
          "desktop-browsers",
          "ai-services",
          "host-components",
        ],
      },
      {
        title: "Confidence",
        surfaceIds: ["testing"],
      },
    ],
    surfaces: [
      {
        id: "cli",
        tagline: "Your own `bb <name>` command",
        title: "bb CLI commands",
        summary:
          "Add a `bb <name>` command for people and agents. With this, a plugin can:",
        bullets: [
          "Run the same command from a terminal, a script, or an agent mid-task",
          "Get argument parsing, `--help`, and JSON errors from one declaration",
          "Know which thread and project it was run from",
        ],
        apiSymbols: [
          "PluginCli",
          "PluginCliResult",
          "defineCli",
          "cliCommand",
          "PluginCliError",
          "PluginCliSpec",
          "PluginCliCommand",
          "PluginCliOption",
          "PluginCliContext",
        ],
        firstParty: [
          "Account Pooler [Experimental]",
          "Automations",
          "bb account",
          "bb cloud AI",
          "bb connect",
          "Browser Automation",
          "Concurrency limit",
          "Custom instructions",
          "Docs",
          "GitHub",
          "Keep Awake",
          "Memory",
          "Modal Sandbox [Experimental]",
          "Provider retry",
          "Push notifications",
          "Secrets",
          "Tasks",
          "Thread list",
          "Workflows",
        ],
      },
      {
        id: "agent-tools",
        tagline: "Native tools, skills, and instructions in every session",
        title: "Agent tools & skills",
        summary:
          "Add tools, skills, and instructions to every agent session. With this, a plugin can:",
        bullets: [
          "Give agents native tools that work like bb's built-in ones",
          "Choose per thread which tools and skills are available",
          "Add instructions to the system prompt when a session starts",
        ],
        apiSymbols: [
          "PluginAgents",
          "PluginAgentToolContext",
          "PluginRowPresentation",
          "PluginRowLabels",
        ],
        firstParty: [
          "Account Pooler [Experimental]",
          "ACP providers",
          "Agent Annotations",
          "Ask User Question",
          "Automations",
          "bb account",
          "bb cloud AI",
          "bb connect",
          "BB guide",
          "Browser Automation",
          "Claude Code provider",
          "Codex provider",
          "Concurrency limit",
          "Custom instructions",
          "Docs",
          "Inline visualizations",
          "Memory",
          "Modal Sandbox [Experimental]",
          "Pi provider",
          "Provider retry",
          "Secrets",
          "Tasks",
          "Theme Preview",
          "Thread list",
          "Workflows",
        ],
      },
      {
        id: "background",
        tagline: "Supervised services and cron schedules",
        title: "Background work",
        summary:
          "Run code on the bb server when no window is open. With this, a plugin can:",
        bullets: [
          "Keep services running, with automatic restarts after a failure",
          "Run jobs on a cron schedule",
          "Set things up once, right after install",
        ],
        apiSymbols: ["PluginBackground", "BbPluginApi.onInstall"],
        firstParty: [
          "Account Pooler [Experimental]",
          "ACP providers",
          "Automations",
          "bb account",
          "bb connect",
          "Concurrency limit",
          "Docs",
          "GitHub",
          "Keep Awake",
          "Modal Sandbox [Experimental]",
          "Push notifications",
          "Side chat",
          "Theme Preview",
          "Workflows",
        ],
      },
      {
        id: "wire",
        tagline: "Typed RPC, HTTP & WebSocket routes, realtime push",
        title: "HTTP, WebSocket, RPC & realtime",
        summary:
          "Use RPC, HTTP, WebSocket, and realtime messages to connect the plugin. With this, a plugin can:",
        bullets: [
          "Call its server from its UI with schema-checked RPC",
          "Receive webhooks and serve HTTP or WebSocket routes",
          "Push live updates to open bb windows",
          "Publish RPC methods other plugins can discover",
        ],
        apiSymbols: [
          "PluginRpc",
          "PluginRpcMethodContract",
          "ExperimentalPluginRpcHandlersWithContext",
          "ExperimentalPluginRpcHandlerContext",
          "ExperimentalPluginRpcCaller",
          "PluginBbSdk.plugins.experimental_discoverRpc",
          "PluginHttp",
          "PluginRealtime",
          "useRpc",
          "PluginRpcClient",
          "useRealtime",
          "useRealtimeConnectionState",
          "PluginRealtimeConnectionState",
          "ExperimentalPluginWebSocket",
          "ExperimentalPluginWebSocketContext",
          "ExperimentalPluginWebSocketHandler",
          "ExperimentalPluginWebSocketHandlers",
          "defineRpcContract",
          "PluginRpcContract",
          "PluginRpcError",
          "PluginRpcHandlers",
        ],
        firstParty: [
          "Account Pooler [Experimental]",
          "ACP providers",
          "Agent Annotations",
          "Automations",
          "bb account",
          "bb cloud AI",
          "bb connect",
          "Browser Automation",
          "Claude Code provider",
          "Codex provider",
          "Concurrency limit",
          "Docs",
          "File Editor",
          "GitHub",
          "Inline visualizations",
          "Keep Awake",
          "Memory",
          "Modal Sandbox [Experimental]",
          "Provider usage",
          "Push notifications",
          "Side chat",
          "Tasks",
          "Theme Preview",
          "Thread list",
          "Workflows",
          "Worktree",
        ],
      },
      {
        id: "thread-events",
        tagline: "React when threads and environments change",
        title: "Lifecycle events",
        summary:
          "Run server code when threads change state or environments are removed. With this, a plugin can:",
        bullets: [
          "React when threads start, finish, fail, are archived or unarchived, or are deleted",
          "Follow queued messages, including ones cancelled before dispatch",
          "Get the provider's error and rate-limit windows when a turn fails",
          "Observe successful environment removal with its previous machine and path",
        ],
        apiSymbols: [
          "PluginEvents",
          "PluginThreadEventPayloads",
          "PluginTurnFailedEvent",
        ],
        firstParty: [
          "Automations",
          "bb connect",
          "Browser Automation",
          "Concurrency limit",
          "Modal Sandbox [Experimental]",
          "Provider retry",
          "Provider usage",
          "Push notifications",
          "Tasks",
          "Workflows",
        ],
      },
      {
        id: "dispatch-hook",
        tagline: "Decide whether a message may go",
        title: "Dispatch hook",
        summary:
          "Run a check before each message reaches an agent. With this, a plugin can:",
        bullets: [
          "Let a message go, queue it with a reason, or refuse it",
          "See the thread, project, machine, and prompt before the turn runs",
          "Hold messages until a condition clears, such as a concurrency limit",
          "Leave people a Send now override",
        ],
        apiSymbols: [
          "PluginHooks",
          "PluginHookSignatures",
          "MessageDispatchHookContext",
          "PluginDispatchEnvironmentIntent",
          "MessageDispatchHookDecision",
        ],
        firstParty: ["Concurrency limit", "Drafts"],
        experimental: true,
      },
      {
        id: "environment-providers",
        tagline: "Provision where a thread runs",
        title: "Environment providers",
        summary:
          "Provide new places a thread can run, picked like any environment. With this, a plugin can:",
        bullets: [
          "Create a workspace for each thread, such as a worktree or a cloud checkout",
          "Ask for inputs, such as a branch, on the new-thread screen",
          "Stream setup progress, and clean up when the thread is done",
          "Restore a thread's workspace after it was removed",
        ],
        apiSymbols: [
          "PluginEnvironments",
          "PluginEnvironmentProviderDeclaration",
          "PluginEnvironmentProviderRequirements",
          "PluginEnvironmentValidateDecision",
          "PluginEnvironmentProviderInputsRegistration",
          "PluginEnvironmentProviderInputsProps",
          "PluginEnvironmentProviderInputsChange",
          "experimental_BranchPicker",
          "BranchPickerProps",
          "experimental_useBranches",
          "UseBranchesArgs",
          "BranchesState",
          "experimental_useCheckoutState",
          "UseCheckoutStateArgs",
          "CheckoutState",
          "PluginEnvironmentProviderDefinition",
          "PluginEnvironmentProviderInputsSchema",
          "PluginEnvironmentProviderPolicy",
          "PluginEnvironmentProviderValidateContext",
          "PluginEnvironmentProviderAvailabilityContext",
          "PluginEnvironmentProviderAvailability",
          "PluginEnvironmentProviderCreateContext",
          "PluginEnvironmentProviderRestoreContext",
          "PluginEnvironmentProviderCreateResult",
          "PluginEnvironmentProviderProgress",
          "PluginEnvironmentProviderRemoveContext",
          "PluginEnvironmentProviderRemoveResult",
        ],
        firstParty: [
          "Modal Sandbox [Experimental]",
          "Personal workspace",
          "Project checkout",
          "Worktree",
        ],
        experimental: true,
      },
      {
        id: "machine-providers",
        tagline: "Create and own execution machines",
        title: "Machine providers",
        summary:
          "Provide machines that bb creates and manages, such as cloud sandboxes. With this, a plugin can:",
        bullets: [
          "Create, suspend, resume, and remove machines on demand",
          "Pair them with an [environment provider](environment-providers) for one-step threads",
          "Recover safely after restarts or cancelled creates",
        ],
        apiSymbols: [
          "PluginMachines",
          "PluginBbSdk.hosts.experimental_create",
          "PluginBbSdk.hosts.experimental_getEnrollmentCommand",
          "PluginBbSdk.hosts.experimental_listProviders",
          "PluginBbSdk.hosts.experimental_suspend",
          "PluginBbSdk.hosts.experimental_reconcile",
          "PluginBbSdk.hosts.experimental_resume",
          "PluginBbSdk.hosts.experimental_retryCleanup",
          "PluginMachines.getResource",
          "MachineExecutorRequest",
          "MachineExecutor",
          "MachineBootstrapRequest",
          "MachineBootstrapApi",
          "PluginMachineProviderDeclaration",
          "PluginMachineValidateDecision",
          "PluginMachineProviderInputsRegistration",
          "PluginMachineProviderInputsProps",
          "PluginMachineProviderInputsChange",
          "PluginMachineProviderDefinition",
          "PluginMachineProviderInputsSchema",
          "PluginMachineProviderAvailability",
          "PluginMachineProviderValidateContext",
          "PluginMachineProviderCreateContext",
          "PluginMachineProviderCreateResult",
          "PluginMachineProviderLifecycleContext",
          "PluginMachineProviderProgress",
          "PluginMachineProviderResourceResult",
          "PluginMachineProviderResource",
          "PluginMachineProviderRemoveResult",
        ],
        firstParty: ["Modal Sandbox [Experimental]"],
        experimental: true,
      },
      {
        id: "server-access",
        tagline: "Connect machines to their server",
        title: "Machine server access",
        summary:
          "Provide the connection machines use to reach their bb server. With this, a plugin can:",
        bullets: [
          "Give new machines what they need to enroll, such as a tunnel URL",
          "Appear as a choice in Machines settings and manual setup",
        ],
        apiSymbols: [
          "PluginServerAccess",
          "ServerAccessProviderDeclaration",
          "ServerAccessGrant",
          "PluginHosts.declareSharedPorts",
          "PluginHosts.ensureSharedPortTunnel",
          "PluginSharedPortTunnelIdentity",
        ],
        firstParty: ["bb connect"],
        experimental: true,
      },
      {
        id: "host-workers",
        tagline: "Run code on enrolled machines",
        title: "Host workers",
        summary:
          "Run plugin code on enrolled machines, not only on the server. With this, a plugin can:",
        bullets: [
          "Watch files, hold a wake lock, or run local commands on that machine",
          "Call the worker from server code over typed RPC",
          "Stop leftover processes before a workspace is deleted",
        ],
        apiSymbols: [
          "PluginHosts",
          "experimental_killProcessesWithCwdUnder",
          "experimental_readProcessIdentity",
          "ExperimentalProcessIdentity",
          "experimental_sanitizeInheritedChildProcessEnv",
          "ExperimentalSanitizeInheritedChildProcessEnvArgs",
          "experimental_spawnPortableOutputProcess",
          "experimental_defineHostEntry",
          "ExperimentalHostEntry",
          "ExperimentalHostClient",
          "ExperimentalHostRpcContext",
          "ExperimentalHostRpcHandlers",
          "ExperimentalHostSignals",
          "ExperimentalHostWatchOptions",
          "ExperimentalHostWatchSubscription",
          "ExperimentalHostWorkerLease",
          "ExperimentalHostPaths",
        ],
        firstParty: [
          "ACP providers",
          "Browser Automation",
          "Claude Code provider",
          "Codex provider",
          "Concurrency limit",
          "Keep Awake",
          "Personal workspace",
          "Pi provider",
          "Project checkout",
          "Worktree",
        ],
        experimental: true,
      },
      {
        id: "provider-bridges",
        title: "Provider bridges",
        tagline: "Bring any agent's runtime into bb",
        summary:
          "Run an agent's sessions through a bridge your plugin ships to each machine. With this, a plugin can:",
        bullets: [
          "Translate an agent CLI or SDK into bb's timeline, tool calls, approvals, and usage",
          "Run any Agent Client Protocol agent through the bundled ACP bridge, with no bridge code",
          "Show the agent's own skills, slash commands, and plugins inside bb",
          "Test it against bb's conformance suite and recorded sessions, without a running bb",
        ],
        apiSymbols: [
          "experimental_defineProviderBridge",
          "ProviderBridgeDefinition",
          "ProviderBridgeContext",
          "ProviderBridgeEntry",
          "PROVIDER_BRIDGE_EXPORT_NAME",
          "PROVIDER_BRIDGE_PROTOCOL_VERSION",
          "ThreadDelta",
          "threadDeltaSchema",
          "BridgeCapabilities",
          "experimental_BridgeRecoveryError",
          "experimental_toolPresentation",
          "experimental_resolveExecutablePath",
          "experimental_recordProviderChildIo",
          "experimental_acpProviderBridge",
          "AcpLaunchSpec",
          "experimental_acpLaunchSpecSchema",
          "experimental_probeAcpAgent",
          "AcpDialect",
          "experimental_nativeRootsHostContract",
          "experimental_filterResolvedNativeRoots",
          "experimental_resolveClaudePluginRoots",
          "experimental_resolveVendorPluginRoots",
          "experimental_createBridgeJsonRpcTestHarness",
          "experimental_runBridgeConformance",
          "experimental_replayRecording",
        ],
        firstParty: [
          "ACP providers",
          "Claude Code provider",
          "Codex provider",
          "Pi provider",
        ],
        experimental: true,
      },
      {
        id: "storage",
        tagline: "Namespaced KV plus your own SQLite",
        title: "Storage",
        summary:
          "Use storage on the bb server that only your plugin can see. With this, a plugin can:",
        bullets: [
          "Keep small values such as flags and cursors in a key-value store",
          "Get its own SQLite database with migrations",
          "Keep internal credentials out of settings",
        ],
        apiSymbols: ["PluginStorage"],
        firstParty: [
          "Account Pooler [Experimental]",
          "Agent Annotations",
          "Automations",
          "bb account",
          "bb cloud AI",
          "bb connect",
          "Browser Automation",
          "Concurrency limit",
          "Custom instructions",
          "Docs",
          "GitHub",
          "Keep Awake",
          "Memory",
          "Modal Sandbox [Experimental]",
          "Push notifications",
          "Side chat",
          "Tasks",
          "Thread list",
          "Workflows",
        ],
      },
      {
        id: "bb-sdk",
        tagline: "Create threads and projects from plugin code",
        title: "The bb SDK",
        summary:
          "Use bb's own API from plugin server code. With this, a plugin can:",
        bullets: [
          "Create threads, send messages, and manage projects and machines",
          "Do what the [bb CLI](cli) and the app can do",
          "Have the threads it creates attributed to the plugin",
          "Start plugin updates in the background and follow their progress or rollback",
        ],
        apiSymbols: [
          "BbPluginApi",
          "PluginServerApi",
          "PluginBbSdk.hosts.get",
          "PluginBbSdk.hosts.experimental_discoverRepos",
          "PluginBbSdk.experimental_promptHistory.list",
          "PluginBbSdk.environments.experimental_cleanup",
          "PluginBbSdk.plugins.experimental_getSafeMode",
          "PluginBbSdk.plugins.experimental_setSafeMode",
          "PluginBbSdk.plugins.experimental_pruneCache",
          "PluginBbSdk.plugins.experimental_startUpdate",
          "PluginBbSdk.plugins.experimental_updateJobs",
          "PluginBbSdk.threads.queuedMessages.experimental_holdForEdit",
          "PluginBbSdk.threads.queuedMessages.experimental_releaseEditHold",
        ],
        firstParty: [
          "Account Pooler [Experimental]",
          "ACP providers",
          "Automations",
          "bb cloud AI",
          "bb connect",
          "Browser Automation",
          "Claude Code provider",
          "Codex provider",
          "Concurrency limit",
          "Docs",
          "File Editor",
          "GitHub",
          "Inline visualizations",
          "Keep Awake",
          "Modal Sandbox [Experimental]",
          "Project checkout",
          "Provider retry",
          "Provider usage",
          "Push notifications",
          "Secrets",
          "Side chat",
          "Storage & retention [Experimental]",
          "Tasks",
          "Theme Preview",
          "Thread list",
          "Workflows",
          "Worktree",
        ],
      },
      {
        id: "thread-plugin-metadata",
        tagline: "Keep plugin data with a thread",
        title: "Thread plugin metadata",
        summary:
          "Use a private JSON record on each thread. With this, a plugin can:",
        bullets: [
          "Keep plugin data with the thread it belongs to, hidden from the model",
          "Seed it when spawning or forking a thread",
          "Read it when configuring that thread's agent",
        ],
        apiSymbols: [
          "PluginBbSdk",
          "PluginAgentConfigurationContext",
          "ReadonlyJsonValue",
          "BbPluginApi",
        ],
        firstParty: ["Workflows"],
      },
      {
        id: "desktop-browsers",
        title: "Desktop browser control",
        tagline: "Use your automation tool on BB-owned tabs",
        summary:
          "Use bb's desktop browser tabs from plugin code. With this, a plugin can:",
        bullets: [
          "Open signed-in tabs that belong to a thread",
          "Give an automation tool private control of a tab",
          "Copy a profile's sign-in from another browser",
        ],
        apiSymbols: [
          "ExperimentalDesktopBrowsersArea",
          "ExperimentalDesktopBrowserScope",
          "ExperimentalDesktopBrowserLease",
          "ExperimentalDesktopBrowserCreateInput",
          "ExperimentalDesktopBrowserAcquireInput",
          "ExperimentalDesktopBrowsersArea.listImportSources",
          "ExperimentalDesktopBrowsersArea.importCookies",
        ],
        firstParty: ["Browser Automation"],
        experimental: true,
      },
      {
        id: "ai-services",
        tagline: "Write bb's titles, commit messages, and transcripts",
        title: "AI services",
        summary:
          "Provide the models that write bb's titles, commit messages, and transcripts. With this, a plugin can:",
        bullets: [
          "Write thread titles and commit messages with any model",
          "Transcribe voice input from the microphone button",
          "Appear as a choice in Settings → AI services",
        ],
        apiSymbols: [
          "PluginAiServices",
          "PluginAiServiceDeclaration",
          "PluginAiServiceStatus",
        ],
        firstParty: ["bb cloud AI", "Codex provider"],
        experimental: true,
      },
      {
        id: "host-components",
        tagline: "Embed bb's chat and prompt box",
        title: "Host components",
        summary:
          "Use bb's own chat, prompt box, and pickers inside plugin pages. With this, a plugin can:",
        bullets: [
          "Embed a thread, a new-thread prompt box, or a textarea with editable voice input",
          "Render Markdown, code, diffs, and file links, and copy text, the way bb does",
          "Add or override app icons",
          "Match bb's styling with no extra work",
        ],
        apiSymbols: [
          "experimental_Icon",
          "experimental_ProviderIcon",
          "ExperimentalProviderIconProps",
          "ExperimentalIconProps",
          "ExperimentalIconRegistration",
          "ExperimentalAppIcons",
          "PluginAppBuilder.experimental_icons",
          "ThreadChat",
          "Markdown",
          "MarkdownProps.experimental_document",
          "experimental_NewThreadComposer",
          "experimental_VoiceInputTextarea",
          "ExperimentalVoiceInputTextareaProps",
          "experimental_ProviderModelPicker",
          "ExperimentalProviderModelPickerProps",
          "experimental_PermissionModePicker",
          "ExperimentalPermissionModePickerProps",
          "experimental_SourceCode",
          "SourceCodeProps",
          "experimental_Diff",
          "DiffProps",
          "experimental_useCodeTheme",
          "PluginCodeThemeState",
          "experimental_copyToClipboard",
          "ExperimentalClipboardContent",
          "UrlLink",
          "UrlLinkProps",
          "experimental_FileLink",
          "ExperimentalFileLinkProps",
          "ExperimentalLiveFileTarget",
          "ExperimentalFileLocation",
          "ExperimentalFileOpenOptions",
          "BbNavigate.openUrl",
          "BbNavigate.experimental_openFilePreview",
          "BbNavigate.experimental_openFileExternally",
        ],
        firstParty: [
          "Account Pooler [Experimental]",
          "Automations",
          "bb account",
          "bb connect",
          "Docs",
          "File Editor",
          "GitHub",
          "Inline visualizations",
          "Provider usage",
          "Side chat",
          "Tasks",
          "Thread list",
        ],
      },
      {
        id: "testing",
        tagline: "Unit-test every surface without a running bb",
        title: "Testing harnesses",
        summary:
          "Use test harnesses that run without bb. With this, a plugin can:",
        bullets: [
          "Test server code against an in-process fake bb server",
          "Render UI slots under vitest",
          "Drive host workers without a machine",
        ],
        apiSymbols: [
          "createFakePluginHost",
          "renderSlot",
          "createFakeSdk",
          "experimental_createHostEntryHarness",
          "loadPluginApp",
          "mountPluginContentScripts",
          "installTestPluginRuntime",
          "experimental_scanPublicSdkOnly",
        ],
        firstParty: [
          "Account Pooler [Experimental]",
          "ACP providers",
          "Agent Annotations",
          "Ask User Question",
          "Automations",
          "bb account",
          "bb cloud AI",
          "bb connect",
          "BB guide",
          "Browser Automation",
          "Claude Code provider",
          "Codex provider",
          "Concurrency limit",
          "Custom instructions",
          "Docs",
          "Drafts",
          "File Editor",
          "GitHub",
          "Inline visualizations",
          "Keep Awake",
          "Memory",
          "Modal Sandbox [Experimental]",
          "PDF preview",
          "Personal workspace",
          "Pi provider",
          "Project checkout",
          "Provider retry",
          "Provider usage",
          "Push notifications",
          "Secrets",
          "Send later",
          "Side chat",
          "Tasks",
          "Theme Preview",
          "Thread list",
          "Workflows",
          "Worktree",
        ],
      },
    ],
  },
];

export const GROUP_BY_SURFACE_ID: ReadonlyMap<
  string,
  { id: SurfaceGroup["id"]; title: string }
> = new Map(
  SURFACE_GROUPS.flatMap((group) =>
    group.surfaces.map(
      (surface) => [surface.id, { id: group.id, title: group.title }] as const,
    ),
  ),
);

export const SURFACES_BY_ID: ReadonlyMap<string, PluginSurface> = new Map(
  SURFACE_GROUPS.flatMap((group) =>
    group.surfaces.map((surface) => [surface.id, surface] as const),
  ),
);
